---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "https://data.brisbane.qld.gov.au/api/explore/v2.1/catalog/datasets/waste-collection-days-collection-days/records?where=suburb%20like%20%27{{ suburb }}%27%20and%20house_number%20%3D%20%27{{ housenumber  }}%27%20and%20street_name%20like%20%27{{ streetname  }}%27{% if unitnumber != \"\" %}and%20unit_number%20%3D%20%27{{ unitnumber  }}%27%20{% endif %}&limit=10&offset=0&timezone=UTC&include_links=false&include_app_metas=false\r\nhttps://data.brisbane.qld.gov.au/api/explore/v2.1/catalog/datasets/waste-collection-days-collection-weeks/records?order_by=week_starting%20asc&limit=26&offset=0&timezone=UTC&include_links=false&include_app_metas=false"
polling_headers: ''
polling_body: ''
id: 240601
custom_fields:
- keyname: author_bio
  field_type: author_bio
  name: Brisbane Bin Collection
  description: Bin Collection for Brisbane Australia
  category: life,productivity
  github_url: https://github.com/alisterscott/trmnl-bne-bin
- keyname: bintypes
  field_type: select
  name: Bin Types
  help_text: Use <kbd>âŒ˜</kbd>+<kbd>click</kbd> or <kbd>ctrl</kbd>+<kbd>click</kbd> to select and deselect multiple options.
  default: red
  options:
  - red
  - yellow
  - green
  multiple: true
- keyname: housenumber
  field_type: number
  name: House Number
  placeholder: '111'
- keyname: unitnumber
  field_type: number
  name: Unit Number
  description: Optional
  optional: true
- keyname: streetname
  field_type: string
  name: Street Name
  placeholder: Dudley St
- keyname: suburb
  field_type: text
  name: Suburb
  placeholder: Annerley
name: BNE BIN Collection
refresh_interval: 30
